-- warehouse shipping order 945
drop table if exists shipping_945 cascade ;
create table if not exists shipping_945
(
	customer_order_id varchar(100) not null,
	actual_pickup_date varchar(100) null,
	vics_bol varchar(100) null,
	hub_groups_order_number varchar(100) null,
	purchase_order_number varchar(100) null,
	mater_vics_bol varchar(100) null,
	link_sequence_number varchar(100) null,
	sf_company_name varchar(100) null,
	sf_seller_buyer varchar(100) null,
	sf_location_id_code varchar(100) null,
	sf_address_info varchar(100) null,
	sf_city varchar(100) null,
	sf_state varchar(100) null,
	sf_zipcode varchar(100) null,
	sf_country_code varchar(100) null,
	st_company_name varchar(100) null,
	st_seller_buyer varchar(100) null,
	st_location_id_code varchar(100) null,
	st_address_info varchar(100) null,
	st_city varchar(100) null,
	st_state varchar(100) null,
	st_zipcode varchar(100) null,
	st_country_code varchar(100) null,
	mf_company_name varchar(100) null,
	mf_seller_buyer varchar(100) null,
	mf_location_id_code varchar(100) null,
	mf_address_info varchar(100) null,
	mf_city varchar(100) null,
	mf_state varchar(100) null,
	mf_zipcode varchar(100) null,
	mf_country_code varchar(100) null,
	bt_company_name varchar(100) null,
	bt_seller_buyer varchar(100) null,
	bt_location_id_code varchar(100) null,
	bt_address_info varchar(100) null,
	bt_city varchar(100) null,
	bt_state varchar(100) null,
	bt_zipcode varchar(100) null,
	bt_country_code varchar(100) null,
	pro_number varchar(100) null,
	master_bol_number varchar(100) null,
	service_level varchar(100) null,
	delivery_appointment_number varchar(100) null,
	purchase_order_date varchar(100) null,
	transportation_mode varchar(100) null,
	carriers_scac_code varchar(100) null,
	carriers_name varchar(100) null,
	payment_method varchar(100) null,
	allowance_or_charge_total_amount varchar(100) null,
	total_units_shipped varchar(100) null,
	total_weight_shipped varchar(100) null,
	lading_quantity varchar(100) null,
	unit_or_basisvfor_measurement_code varchar(100) null,
	created_by varchar(30) not null,
	created_on timestamp not null default current_timestamp,
	last_update_by varchar(30) null,
	last_update_on timestamp null,
	primary key(customer_order_id)
);  
drop table if exists shipping_945_dtl cascade ;
create table if not exists shipping_945_dtl
(
	customer_order_id varchar(100) not null,
	assigned_number int not null,
	pallet_id varchar(100) null,
	carrier_tracking_number  varchar(100) null,
	shipment_status  varchar(100) null,
	requested_quantity  varchar(100) null,
	actualquantity_shipped  varchar(100) null,
	difference_between_actual_and_requested  varchar(100) null,
	unit_or_basis_measurement_code  varchar(100) null,
	upc_code  varchar(100) null,
	sku_no  varchar(100) null,
	lot_batch_code  varchar(100) null,
	total_weight_for_item_line  varchar(100) null,
	retailers_item_number  varchar(100) null,
	line_number  varchar(100) null,
	expiration_date  varchar(100) null,
	primary key(customer_order_id, assigned_number)
);